# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-19 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200218_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ticket_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_id',
            field=models.IntegerField(default=5555),
        ),
    ]
