# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200219_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
