# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200220_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uid_votes',
            field=models.TextField(default=''),
        ),
    ]
