# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_uid_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('ticket_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='number_votes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='uid_votes',
        ),
    ]
