# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200221_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number_votes',
            field=models.IntegerField(default=0),
        ),
    ]
