# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_number_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('ticket_id', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('payment_id', models.CharField(max_length=30)),
            ],
        ),
    ]
