# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('BUG', 'Bug Report'), ('FEATURE', 'Feature Request')], default='FEATURE', max_length=7),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
