# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20200307_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
